### PR TITLE
Support `sessionVariables` option

### LINKED ISSUE #210: [feature]Support `sessionVariables` configuration properties
**Is your feature request related to a problem? Please describe.**
R2DBC MySQL lacks sessionVariable configuration properties, limiting session customization compared to MySQL Connector/J.

**Describe the solution you'd like**
Implement sessionVariable configuration in R2DBC MySQL to allow setting session-level variables directly from the connection URL.

**Additional context**
mysql dev doc: https://dev.mysql.com/doc/connector-j/en/connector-j-connp-props-session.html
feature request tracked at: https://github.com/mirromutth/r2dbc-mysql/issues/191

### PR DESCRIPTION
**Pull request by mirromutth**
Motivation:

See also #210 

Modification:

- [x] Add session variables splitting method
- [x] Add an option and a configuration property `sessionVariables`
- [x] Set session variable before loading server variables, i.e. `SELECT @@transaction_isolation ...`

Result:

Support `sessionVariables`

### CODE REVIEW

**Review by jchrys — APPROVED** [review]
LGTM

**Comment by jchrys** [comment]
Missed it but I think need to update the doc as well

**Comment by mirromutth** [comment]
I added the doc to [wiki page](/asyncer-io/r2dbc-mysql/wiki/Configuration-Options#sessionvariables), this should be a good start for more concise docs.

**Comment by jchrys** [comment]
> I added the doc to [wiki page](/asyncer-io/r2dbc-mysql/wiki/Configuration-Options#sessionvariables), this should be a good start for more concise docs.

Fantastic! Thank you for kicking things off 👍

**Review by jchrys — APPROVED** [review]

**Pull request merged**
