### PR TITLE
Adding jobs for Java 11 and Java 17.

### PR DESCRIPTION
**Pull request by saurabhyadavdev**
Motivation: Currently compatibility tests are only for Java 8. Need to add more tests for other LTS version Java 11 & 11.

Modifications: Added new jobs for Java v11 & v 17 in unit-tests workflow and removed -WError argument in POM.xml for maven-compiler-plugin to fix failing Java 17 build.

Result: Jobs for Java 8, 11, 17 run to check compatibility

#77 .github/workflows/unit-tests.yml has job for Java 8. As part of this PR adding jobs for Java 11 and Java 17.

### CODE REVIEW

**Comment by jchrys** [comment]
Hello, @saurabhyadav1985.
Thanks a lot for your hard work on this issue.
Could you  remove `-Werror` arguments from pom.xml's `maven-compiler-plugin` section as well? (I think it might fix build_java_17 and I don't think that option is useful)

+ Could you make your commit message follow below template like other commits?

```
title

Motivation:

Modifications:

Result:

```

**Comment by saurabhyadavdev** [comment]
Updated PR with the suggested changes.

**Review by jchrys — APPROVED** [review]

**Comment by jchrys** [comment]
Thanks a lot!

**Comment by aalmiray** [comment]
May I suggest using a matrix https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs to reduce duplication? `java-version` is the only value that's really different across the 3 build jobs.

**Comment by jchrys** [comment]
Thank you for the suggestion, @aalmiray.
I appreciate your valuable input.
Could you please let me know if you would be interested in making a PR?

**Comment by aalmiray** [comment]
I'd suggest opening another issue and tag it with "good first issue". That's how I found this one 😅

**Comment by jchrys** [comment]
got it! Thanks for let me know. 😄

**Pull request merged**
