### PR TITLE
Fix request queue delaying

### PR DESCRIPTION
**Pull request by jchrys**
Motivation:
The request queue could contain cancelled tasks, which caused delays and stalls.

Modification:
Implemented Filtered out cancelled tasks from the queue.

Result:
The queue now functions better.
Resolves issue #114

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
Hi @jchrys , thanks for the fix!

After manual testing, these changes seem to reduce the pending rate but may not completely resolve the problem, please see my local test result:

image

**Comment by jchrys** [comment]
Oh, Let us check again. Thanks for your feedback.

**Comment by JohnNiang** [comment]
I found that the `RequestQueue` was always active if I requested a pending API at browser, please see the logs:

```java
2023-05-29T15:36:51.279+08:00  INFO 34671 --- [ctor-http-nio-7] i.a.r2dbc.mysql.client.RequestQueue      : Submitting new task: io.asyncer.r2dbc.mysql.client.RequestTask@1e9a5e35, queue status: 1
2023-05-29T15:36:51.280+08:00  INFO 34671 --- [ctor-http-nio-7] i.a.r2dbc.mysql.client.RequestQueue      : Queue is in active
2023-05-29T15:36:51.533+08:00  INFO 34671 --- [ctor-http-nio-8] i.a.r2dbc.mysql.client.RequestQueue      : Submitting new task: io.asyncer.r2dbc.mysql.client.RequestTask@596f13fd, queue status: 1
2023-05-29T15:36:51.533+08:00  INFO 34671 --- [ctor-http-nio-8] i.a.r2dbc.mysql.client.RequestQueue      : Queue is in active
2023-05-29T15:36:51.713+08:00  INFO 34671 --- [ctor-http-nio-9] i.a.r2dbc.mysql.client.RequestQueue      : Submitting new task: io.asyncer.r2dbc.mysql.client.RequestTask@4f0fbfd7, queue status: 1
2023-05-29T15:36:51.720+08:00  INFO 34671 --- [ctor-http-nio-9] i.a.r2dbc.mysql.client.RequestQueue      : Queue is in active
```

The code I changed was as follows:

```java
    <T> void submit(RequestTask<T> task) {
        LOGGER.info("Submitting new task: {}, queue status: {}", task, status);
        if (STATUS_UPDATER.compareAndSet(this, IDLE, ACTIVE)) {
            // Fast path for general way.
            LOGGER.info("Queue is in idle.");
            task.run();
            return;
        }

        LOGGER.info("Queue is in active");

        // Check dispose after fast path failed.
        int status = this.status;
```

**Comment by jchrys** [comment]
Fixed and passed heavy load test. PTAL @JohnNiang, @mobidick1969

**Comment by jchrys** [comment]
currently in fixing

**Review by JohnNiang — APPROVED** [review]
Nice work!

It works very well for me.

**Review by JohnNiang — APPROVED** [review]
Nice work!

It works very well for me.

**Comment by jchrys** [comment]
@JohnNiang Thanks very much for your valuable report & contribution. The fix has been released. (both 1.0.2, 0.9.3)

**Pull request merged**
