### PR TITLE
Implementing Checkstyle

### PR DESCRIPTION
**Pull request by jchrys**
Motivation:
To ensure code consistency and quality through the adoption of Checkstyle

Modification:
Added Checkstyle plugin and configuration, updated code to comply with new coding standards.
Set version as INTERNAL on internal modules

Result:
Enhanced code quality and consistency across the project, facilitating easier contributions and maintenance.

### CODE REVIEW

**Comment by mirromutth** [comment]
Is there any new progress? I suggest moving this PR to 1.1.3.

**Comment by jchrys** [comment]
> Is there any new progress? I suggest moving this PR to 1.1.3.

Got it. Let me move this and others.

**Comment by jchrys** [comment]
> Is there any new progress? I suggest moving this PR to 1.1.3

@mirromutth
Done. I believe you're ready to release (I sent you the necessary credentials earlier this year via email) feel free to let me know if you don't have oneIf you don't have them, please inform me, and I'll be happy to assist with the release process.

**Comment by jchrys** [comment]
@mirromutth
Following the merge of https://github.com/asyncer-io/r2dbc-mysql/pull/243, it appears that tests within Micronaut are failing.

**Review by mirromutth — APPROVED** [review]
LGTM

**Pull request merged**
